apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    volume: database
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: nfs
  # Recycle
  # Delete 
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  nfs:
    server: 142.93.71.87
    path: /nfsshare

